### ISSUE TITLE
Task: List reading material for participants

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#13]
# Task Description
We list reading material to prepare participants to take part to the workshop. 
The material should cover the basics of data theory, computational social science, networks, IOT, digital twins, AI, multimodal data, time machine

# List of actions
- [ ] Action: Find one fundamental document per topic 
- [ ] Action: Order document in levels of complexity
- [ ] Actino: Output reading list with links as md and PDF

**Comment by sjinko** [comment]
See syllabus
