### ISSUE TITLE
Task: Write short description of workshop

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#15]
# Task Description
As to communicate on the workshop (syllabus, email and GH and website), we synthetise the main components into a synthetic description which features rational, objectives, means, process and outcomes.

This could be based on the short description sent to M. Zahedi 

# List of actions
- [ ] Action: Draft description 
- [ ] Action: Share with team
- [ ] Wait for feedback from @danecas
- [ ] Wait for feedback from @neriiacopo

**Comment by sjinko** [comment]
Hi @danecas, do you have a short description of the handson workshop I can share?
