### ISSUE TITLE
Task: Write description of main exercice

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#19]
# Task Description
Based on discussion on Nov. 18 and proposition by DN, we structure the course around a exercise / output: a pipeline to process multimodal data on urban landscapes and environments, linkig it with data from BH and research interests of participants

# List of actions
- [ ] Action: Draft description of output / exercise 
- [ ] Action: Share with team
- [ ] Wait for feedback from @sjinko
- [ ] Wait for feedback from @noriiacopo
