### ISSUE TITLE
Task: Email umontreal PhD and MSc students to announce course

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#23]
# Task Description
Send an information email to PhD and MSc Students (VTP and Design Theory) to invite them to pre-register for the course

# List of actions
- [ ] Action: Draft email 
- [ ] Action: Send email to PhD students
- [ ] Action: Email C. Lourandes to email VTP students
- [ ] Action: Email ??? to email Design theory students
