### ISSUE TITLE
Task: Create pre-registration form on Google Form

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#24]
# Task Description
To know how many student would participate, create a pre-registration form on Google Forms

# List of actions
- [x] Action: Create pre-registration form 
- [x] Action: Add link to Linktr.ee
- [x] Action: Add link to email to students
