### ISSUE TITLE
Task: Invite F. Kaplan for lecture

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#29]
# Task Description
We attempt to invite F. Kaplan to lecture
F. Kaplan says he is interested but can only confirm second week of Jan.

# List of actions
- [x] Action: Email F. Kaplan 
- [x] Wait for feedback from F. Kaplan
- [x] Action: Response to F. Kaplan’s email
- [ ] Action: Email reminder to F. Kaplan by Jan. 9
