### ISSUE TITLE
Task: Write syllabus for umontreal course AME6201

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#31]
# Task Description
In compliance with umontreal guidelines on syllabus, @sjinko prepares syllabus for course

Workshop description : https://docs.google.com/document/d/1pj6hwabUzRME4s4zwV11aGBWuziJ-sWhxPEL57ONqxg/edit?usp=sharing

# List of actions
- [x] Action: Structure md file according to umontreal syllabus contents
- [x] Action: Discuss with Dario on Feb. 21
- [x] Action: Make last changes to programme
- [x] Action: Add workshop description 
- [x] Action: Review evaluation criterias
- [x] Action: message students
