### ISSUE TITLE
Meeting: Internal organization on Feb. 21

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#35]
# Task Description
Describe this task here

# List of actions
- [ ] Action: 
- [ ] Action:

**Comment by sjinko** [comment]
## Welcoming lunch
- [ ] Shin’s 10 min. speech (no screen)
- [ ] Stress that what we doing is hands on and bottom up, more research focused, more pragmatic, away from institutional big projects. Don't set expectations about what we are going to do
- [ ] Dario introduce Varsi as an excuse to discuss
- [ ] Inform students of slight changes to schedule

**Comment by sjinko** [comment]
https://docs.google.com/spreadsheets/d/17c5reFLB3gHk1jn0lJo0nupytcvScNA5mEgcdVymFyQ/edit?usp=sharing
