### ISSUE TITLE
Task: Make poster for Datathink 2023

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#9]
# Task Description
In the spirit of the previous editions, we have a poster made. It should be in the lineage of the previous editions, while kickstarting a new cycle.

## Info: 

* Séminaire doctoral international
* Savoirs et outils numériques
* 27.02 – 03.03 2023
* Rome, Italie

## logos:
* unesco chair
* University of Zurich
* DVS
* BH
* Max-Planck
* umontreal DAI
* Fonds Sid Lee Architecture

![](https://www.avalanche.studio/wp-content/uploads/2019/01/datathink-mockup-2560x1440.jpg)

# List of actions
- [x] Action: Ask M. Bally to send original indd file 
- [x] Action: Chose / create new image ? change color ?
- [x] Action: Upload all logos to repo
- [x] Action: Update indd file with new info in [communication/logos](https://github.com/CUPUM/ame6201-organisation/tree/management/communication/logos) of the **management branch**
- [x] Action: Add chair’s pastille

**Comment by sjinko** [comment]
@danecas, Ideally, I would like that it matches out graphic chart. Do you have any requirement on your side?

**Comment by sjinko** [comment]
Hi Dario,

For the poster and com, we would need the following logos in **white (.eps files): 
* University of Zurich
* DVS
* Max-Planck Society
* Bibliotheca Hertziana

You can upload them to the [communication/logo](management branch) folder **on the management branch** (I have create a separate branch from the main to host all documents used in the organization / management of the course.

**Comment by sjinko** [comment]
Hola @danecas, I would like to output the posters this week to start recruiting students. Could you please upload the logos here : https://github.com/CUPUM/ame6201-organisation/tree/management/communication/logos
